sudo: required

services:
  - docker

before_install: |
  curl -O https://bin.equinox.io/c/jewmwFCp7w9/convox-stable-linux-amd64.tgz &&\
  tar zxvf convox-stable-linux-amd64.tgz -C /tmp

script:
  convox doctor

after_success:
  - convox deploy --app cv-soulshake-net --rack personal/legit
